spring:
  application:
    name: sales-api
server:
  port: 8080

zuul:
  routes:
#    leads-api:
#      path: /leads1/**
#      url:  http://10.0.6.96:8081/hozon
#      serviceId: leads
    sales-mng-web:
      sensitiveHeaders:
      path: /hozon/**
     # url: http://10.111.16.174:8080/hozon
      url:  http://10.0.6.96:8081/hozon
    appservice:
      sensitiveHeaders:
      path: /appservice/**
      url:  http://10.0.6.96:8090
  ignored-services: '*'
  host:
    max-per-route-connections: 100
    max-total-connections: 300
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
    SocketTimeout: 60000

  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000



eureka:
  client:
    service-url:
      defaultZone: http://10.0.6.96:9020/eureka/
